name: Covid-Framework-build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - uses: docker/build-push-action@v2.6.1
    - name: docker build covid-app
      run: docker build ../../Dockerfile -t covidframework-server-image:latest
      
