name: Covid-Framework-build
on: 
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v2.6.1
    - name: docker build covid-app
      run: docker build ../../Dockerfile -t covidframework-server-image:latest
      
