name: Covid-Framework-build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
        
      - 
        name: Build Image
        uses: docker/build-push-action@v2
        with:
          tags: latest, ${{ github.run_number}}
          file: ../../Dockerfile
          
      - 
        name: Log into Github container
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.3.0
        with:
          images:
            ghcr.io/covid-app
          flavor:
            latest=false
          tags:
            type=raw, value=latest
      -
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          builder: ${{steps.buildx.outputs.name}}
          cache-from: type=local, src=/tmp/.buildx-cache
          cache-to: type=local, dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request'}}
          tags: ${{ steps.docker_meta.outputs.tags}}
          labels: ${{ steps.docker_meta.outputs.labels }}
      -
        name: Show image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
   
      
