name: Covid-Framework-build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Log into Github container
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{github.actor}} --password-stdin
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          tags: covid-app:v1
          file: ../../Dockerfile
      
   
      
